apiVersion: apps/v1
kind: Deployment
metadata:
  name: mizdooni-react-app
  # namespace: vivaldi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mizdooni-react-app
  template:
    metadata:
      labels:
        app: mizdooni-react-app
    spec:
      containers:
        - name: react-app
          image: sapidgirl/react-app:latest
          ports:
            - name: http
              containerPort: 3000
          # resources:
          #   limits:
          #     cpu: 0.2
          #     memory: "10Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-svc
  labels:
    app: mizdooni-react-app
spec:
  type: NodePort
  selector:
    app: mizdooni-react-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
